# Generated by Django 4.0.2 on 2022-02-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_dialog_alter_message_managers_remove_message_message_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
